dbt_vault:
  outputs:
    dev:
      account: kz01230.ap-southeast-2
      database: TRIAL_LANDING_DB
      role: TRIAL_LANDING_ROLE
      schema: RAW
      threads: 1
      type: snowflake
      user: "{{ env_var('dbt_user') }}"
#      TRIAL_LANDING_USER
      password: "{{ env_var('dbt_password') }}"
#      happy*goose*optical
      warehouse: TRIAL_LANDING_WAREHOUSE
  target: dev